### ISSUE TITLE
PW apidev webpage not working

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#278] opened 2016-04-14 11:55 UTC
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=PW&key=BUBUtkAra

It gives blank page.

All other dictionaries give proper pages. Only PW seems to have an issue.
@funderburkjim It is sort of urgent. I want to complete the bigrams submissions soon.

**Comment by funderburkjim** [comment] 2016-04-15 03:12
The link above is working now.

Here's the problem.

I'm using sqlite for database.   That is good in many ways, but it has one flaw, which I've encountered several times.

The problem comes when a sqlite database is updated  AND when, at the same instant, someone is doing some web request involving that database.   When this occurs, the file appears to be owned by the web user, and the sqlite update fails, or the file becomes corrupted.  Also, when this occurs, there is no terminal error showing the problem.  

I've had this occur several times, with both MW and PW, and occasionally with other dictionaries.  Tonight, I noticed it with PW and reran the appropriate update program, and that's why the problem is now fixed.

I haven't thought of a simple way to test for when this problem occurs.  Any suggestions.

**Comment by drdhaval2785** [comment] 2016-04-15 04:03
Today I have issues in MW72, which was working fine earlier.
PW seems to be fixed now.

**Comment by gasyoun** [comment] 2016-04-15 08:10
`Any suggestions?` - none, other than showing that the site is down.

**Comment by funderburkjim** [comment] 2016-04-15 18:52
@drdhaval2785   

Do you still see the problem?

I expect you are not seeing the problem.

The time of your Github comment above re mw72 (April 15, 2016  12:03AM)  is very close to the
date-time stamp of the relevant MW72 sqlite file at Cologne  (April 15, 2016 12:05 AM).
It may be that you accessed this file while it was under construction.

Since we have people all over the world accessing these files,  there appears to me to be no
'safe' time to recreate the files. 

Please do keep mentioning when you encounter this problem.  If you have the problem for a given dictionary at two different times 5 minutes apart, then I probably need to recreate one of the sqlite files for that dictionary.

**Closed** 2016-05-12 04:06 UTC
Labels: Bug
